#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
REPO_ROOT="/Users/marvingrigg/git-projects/emscherspatzen"
ENV_FILE="$REPO_ROOT/.env"
SHEET_ID="1hANtmFERY5xL_EUv-EV599iO7ic3bcSswo5c_HtkGZI"
SHEET_EDIT_URL="https://docs.google.com/spreadsheets/d/${SHEET_ID}/edit?gid=0#gid=0"
CSV_URL="https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=0"

banner "Emscherspatzen: Auftritte-Pipeline verbinden"

# ── Stage 1: Sheet freigeben & Spalten prüfen ──────────────────────────────
stage "Google Sheet: Freigabe & Spalten"
say "Das Sheet muss öffentlich lesbar sein, damit der Cloudflare-Build es abrufen kann."
open_url "$SHEET_EDIT_URL"
step "Oben rechts 'Freigeben' -> 'Allgemeiner Zugriff' -> 'Jeder mit dem Link' -> Rolle 'Betrachter'."
step "Kopfzeile muss die Spalten Datum, Uhrzeit, Titel, Ort, Beschreibung enthalten (Reihenfolge egal)."
step "Uhrzeit ebenfalls als Text im Format HH:MM eintragen (z.B. 19:30), optional."
step "Datum immer als Text im Format JJJJ-MM-TT eintragen (z.B. 2026-12-14), nicht 14.12.2026."
note "Nur öffentliche Auftritte hier eintragen, keine Proben (siehe CONTEXT.md: Auftritt)."
pause "Freigabe + Kopfzeile gesetzt? Weiter mit Enter."

say "Prüfe, ob das Sheet jetzt öffentlich lesbar ist..."
if curl -sf -o /dev/null "$CSV_URL"; then
  printf '  %s✓ Sheet ist öffentlich lesbar.%s\n' "$GREEN" "$RESET"
else
  warn "Sheet antwortet noch nicht öffentlich (HTTP-Fehler). Freigabe-Einstellung oben nochmal prüfen, dann Wizard erneut ausführen."
fi

write_env AUFTRITTE_SHEET_CSV_URL "$CSV_URL"
note "CSV-URL für lokale Entwicklung in $ENV_FILE gespeichert (nicht committen, ist .gitignored)."

# ── Stage 2: Cloudflare Build-Variable setzen ──────────────────────────────
stage "Cloudflare: Build-Variable setzen"
say "Diese Variable wird nur beim Build gelesen (Astro liest process.env), nicht zur Laufzeit."
open_url "https://dash.cloudflare.com/"
step "Workers & Pages -> euren Worker (emscherspatzen) öffnen."
step "Settings -> Build -> 'Build variables and secrets' -> Variable hinzufügen."
step "Name: AUFTRITTE_SHEET_CSV_URL"
step "Wert (unten stehende URL kopieren):"
say "$CSV_URL"
step "Speichern."
pause "Build-Variable gesetzt? Weiter mit Enter."

# ── Stage 3: Deploy Hook + Apps Script Trigger ─────────────────────────────
stage "Cloudflare Deploy Hook & Apps-Script-Trigger"
say "Der Deploy Hook löst einen Rebuild aus, sobald Norbert das Sheet ändert."
step "Im selben Worker: Settings -> Build -> Deploy Hooks -> 'Create Deploy Hook'."
step "Branch: main. Name z.B. 'google-sheet-auftritte'. Erstellen."
step "Die angezeigte Deploy-Hook-URL kopieren."
ask DEPLOY_HOOK_URL "Deploy-Hook-URL einfügen:"

say "Jetzt im Google Sheet: Erweiterungen -> Apps Script."
step "Vorhandenen Beispielcode löschen, dann diesen Code einfügen:"
printf '\n%s———————————————————————————————————————————————%s\n' "$DIM" "$RESET"
cat <<SCRIPT
const CLOUDFLARE_DEPLOY_HOOK_URL = '${DEPLOY_HOOK_URL}';

function onChange() {
  UrlFetchApp.fetch(CLOUDFLARE_DEPLOY_HOOK_URL, {
    method: 'post',
    muteHttpExceptions: true,
  });
}
SCRIPT
printf '%s———————————————————————————————————————————————%s\n\n' "$DIM" "$RESET"
step "Speichern (Diskettensymbol), Projekt z.B. 'Auftritte Auto-Rebuild' nennen."
step "Links die Uhr (Trigger) -> 'Trigger hinzufügen' — zweimal, beide auf dieselbe Funktion:"
step "  1. Funktion: onChange · Ereignisquelle: Aus Tabelle · Ereignistyp: Bei Änderung -> Speichern"
step "  2. Funktion: onChange · Ereignisquelle: Zeitgesteuert · Typ: Tagestimer · 3 bis 4 Uhr -> Speichern"
say "Der zweite Trigger baut die Seite jede Nacht neu, damit vergangene Auftritte"
say "nicht bis zur nächsten Sheet-Änderung unter 'Bevorstehende' stehenbleiben."
step "Beim ersten Speichern nach Berechtigungen fragen -> eigenes Google-Konto erlauben."
pause "Beide Trigger eingerichtet? Weiter mit Enter."

# ── Stage 4: Verifizieren ──────────────────────────────────────────────────
stage "Verifizieren"
say "Die eben gesetzte Build-Variable wirkt erst ab dem nächsten Build."
step "Im Cloudflare-Dashboard des Workers: letztes Deployment öffnen -> 'Retry deployment' (oder 'Redeploy')."
pause "Rebuild angestoßen? Weiter mit Enter (Build dauert ca. 1-2 Minuten)."
say "Dann zum Testen: im Sheet einen Test-Auftritt eintragen (Datum in der Zukunft) und speichern."
say "Das sollte automatisch einen neuen Build auslösen (Apps-Script-Trigger)."
step "Nach ca. 1-2 Minuten die Live-Seite neu laden und prüfen, ob der Test-Auftritt erscheint."
step "Test-Zeile danach wieder aus dem Sheet löschen."
pause "Auftritt live gesehen? Weiter mit Enter."
# ──────────────────────────────────────────────────────────────────────────

finish
